// For demo purposes, we'll return mock data
// In a real application, you would set up Supabase environment variables and fetch from the database

export async function fetchDashboardData() {
  // Mock data that matches the original HTML report
  return {
    executiveSummary: {
      totalProducts: 231,
      totalSalesVolume: 80050,
      averagePrice: 32.35,
      totalBrands: 48,
      marketLeader: "Kasa",
      marketLeaderShare: 20.99,
      marketLeaderProducts: 8,
      productDistribution: [
        { name: "Light Switches", value: 122 },
        { name: "Dimmer Switches", value: 109 },
      ],
    },
    brandAnalysis: {
      brandCategoryRevenue: [
        { brand: "Kasa", dimmerRevenue: 184012, switchRevenue: 313890 },
        { brand: "Leviton", dimmerRevenue: 127016, switchRevenue: 138958 },
        { brand: "Lutron", dimmerRevenue: 402186, switchRevenue: 107908 },
        { brand: "GE", dimmerRevenue: 76859, switchRevenue: 85015 },
        { brand: "ELEGRP", dimmerRevenue: 130329.5, switchRevenue: 37811 },
        { brand: "BESTTEN", dimmerRevenue: 48181.5, switchRevenue: 38582 },
        { brand: "ENERLITES Store", dimmerRevenue: 6836, switchRevenue: 44973.5 },
        { brand: "Amazon", dimmerRevenue: 24977.5, switchRevenue: 24084 },
        { brand: "Legrand", dimmerRevenue: 19266, switchRevenue: 5916 },
        { brand: "TP-Link", dimmerRevenue: 60289, switchRevenue: 24990 },
      ],
    },
    productAnalysis: {
      priceVsRevenue: [
        {
          category: "Dimmer Switches",
          products: [
            {
              id: "1",
              name: "Kasa Smart 3 Way Dimmer Switch KIT",
              brand: "Kasa",
              price: 42.99,
              unitPrice: 54.99,
              revenue: 85980,
              volume: 2000,
              url: "https://www.amazon.com/dp/B0BC2MWTR9",
            },
            {
              id: "2",
              name: "Lutron Caseta Original Smart Dimmer Switch Kit",
              brand: "Lutron",
              price: 189.9,
              unitPrice: 94.95,
              revenue: 75960,
              volume: 400,
              url: "https://www.amazon.com/dp/B01M3XJUAD",
            },
            {
              id: "3",
              name: "ELEGRP Digital Dimmer Light Switch for 300W",
              brand: "ELEGRP",
              price: 59.99,
              unitPrice: 30.0,
              revenue: 59990,
              volume: 1000,
              url: "https://www.amazon.com/dp/B099RJ2HRN",
            },
            {
              id: "4",
              name: "Kasa Smart Dimmer Switch HS220",
              brand: "Kasa",
              price: 19.98,
              unitPrice: 22.99,
              revenue: 59940,
              volume: 3000,
              url: "https://www.amazon.com/dp/B079775ZZQ",
            },
            {
              id: "5",
              name: "Leviton SureSlide Dimmer Switch",
              brand: "Leviton",
              price: 14.07,
              unitPrice: 28.33,
              revenue: 56280,
              volume: 4000,
              url: "https://www.amazon.com/dp/B0076HPM8A",
            },
            {
              id: "6",
              name: "ELEGRP Digital Dimmer Light Switch for 300W, 10 Pack",
              brand: "ELEGRP",
              price: 89.99,
              unitPrice: 9.0,
              revenue: 44995,
              volume: 500,
              url: "https://www.amazon.com/dp/B094XXG14N",
            },
            {
              id: "7",
              name: "Amico 6 Pack Dimmer Light Switch",
              brand: "GE",
              price: 44.99,
              unitPrice: 7.5,
              revenue: 40491,
              volume: 900,
              url: "https://www.amazon.com/dp/B0D3TBK88B",
            },
            {
              id: "8",
              name: "Lutron Ariadni/Toggler LED+ Dimmer Light Switch",
              brand: "Lutron",
              price: 19.47,
              unitPrice: 25.0,
              revenue: 38940,
              volume: 2000,
              url: "https://www.amazon.com/dp/B006UTQCA2",
            },
            {
              id: "9",
              name: "Lutron Diva Smart Dimmer Switch for Caseta Smart Lighting",
              brand: "Lutron",
              price: 73.9,
              unitPrice: 52.99,
              revenue: 36950,
              volume: 500,
              url: "https://www.amazon.com/dp/B0BSHKS26L",
            },
            {
              id: "10",
              name: "Lutron Maestro LED+ Dual Dimmer and Switch",
              brand: "Lutron",
              price: 71.38,
              unitPrice: 50.0,
              revenue: 35690,
              volume: 500,
              url: "https://www.amazon.com/dp/B0CT3RFY6K",
            },
            {
              id: "11",
              name: "BESTTEN Dimmer Light Switch",
              brand: "BESTTEN",
              price: 38.96,
              unitPrice: 38.96,
              revenue: 27272,
              volume: 700,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "12",
              name: "Lutron Caseta Smart Dimmer Switch",
              brand: "Lutron",
              price: 56.76,
              unitPrice: 28.38,
              revenue: 28380,
              volume: 500,
              url: "https://www.amazon.com/dp/B00KLAXFQA",
            },
            {
              id: "13",
              name: "Kasa Smart Dimmer Switch 3-Way HS220P3",
              brand: "Kasa",
              price: 62.99,
              unitPrice: 21.0,
              revenue: 31495,
              volume: 500,
              url: "https://www.amazon.com/dp/B09HGDL2SY",
            },
            {
              id: "14",
              name: "TREATLIFE Smart Dimmer Switch 4 Pack",
              brand: "TREATLIFE",
              price: 65.99,
              unitPrice: 16.5,
              revenue: 32995,
              volume: 500,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "15",
              name: "TP-Link Tapo Matter Smart Dimmer Switch",
              brand: "TP-Link",
              price: 24.99,
              unitPrice: 24.99,
              revenue: 29988,
              volume: 1200,
              url: "https://www.amazon.com/dp/B0CBNX6Q51",
            },
          ],
        },
        {
          category: "Light Switches",
          products: [
            {
              id: "101",
              name: "Kasa Smart Light Switch HS200P3",
              brand: "Kasa",
              price: 42.99,
              unitPrice: 14.33,
              revenue: 128970,
              volume: 3000,
              url: "https://www.amazon.com/dp/B07HGW8N7R",
            },
            {
              id: "102",
              name: "Kasa Smart Light Switch HS200",
              brand: "Kasa",
              price: 16.99,
              unitPrice: 19.99,
              revenue: 84950,
              volume: 5000,
              url: "https://www.amazon.com/dp/B01EZV35QU",
            },
            {
              id: "103",
              name: "Lutron Caseta 3 Way Smart Dimmer Switch Kit",
              brand: "Lutron",
              price: 69.95,
              unitPrice: 69.95,
              revenue: 69950,
              volume: 1000,
              url: "https://www.amazon.com/dp/B07HM6L48C",
            },
            {
              id: "104",
              name: "Kasa Smart 3 Way Switch HS210 KIT",
              brand: "Kasa",
              price: 33.99,
              unitPrice: 17.0,
              revenue: 67980,
              volume: 2000,
              url: "https://www.amazon.com/dp/B07724HNTX",
            },
            {
              id: "105",
              name: "Philips Hue Smart Dimmer Switch with Remote",
              brand: "GE",
              price: 22.49,
              unitPrice: 3.98,
              revenue: 44980,
              volume: 2000,
              url: "https://www.amazon.com/dp/B08W8GLPD5",
            },
            {
              id: "106",
              name: "Kasa Smart Switch 2-Gang HS200-2",
              brand: "Kasa",
              price: 31.99,
              unitPrice: 31.99,
              revenue: 31990,
              volume: 1000,
              url: "https://www.amazon.com/dp/B0D3KP68S7",
            },
            {
              id: "107",
              name: "Lutron Caseta Original Smart Switch",
              brand: "Lutron",
              price: 59.95,
              unitPrice: 59.95,
              revenue: 29975,
              volume: 500,
              url: "https://www.amazon.com/dp/B017LRCG38",
            },
            {
              id: "108",
              name: "Leviton E5601-MW Decora Edge 15 Amp Single Pole Rocker Switch",
              brand: "Leviton",
              price: 25.98,
              unitPrice: 2.6,
              revenue: 25980,
              volume: 1000,
              url: "https://www.amazon.com/dp/B0C86MJLVH",
            },
            {
              id: "109",
              name: "TP-Link Tapo Matter Smart Light Switch",
              brand: "TP-Link",
              price: 24.99,
              unitPrice: 24.99,
              revenue: 24990,
              volume: 1000,
              url: "https://www.amazon.com/dp/B0CBNX6Q51",
            },
            {
              id: "110",
              name: "Amico 30 Pack Single Pole Light Switch with Wall Plate",
              brand: "Other",
              price: 49.99,
              unitPrice: 1.67,
              revenue: 19996,
              volume: 400,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
            {
              id: "111",
              name: "BESTTEN 10 Pack Single Pole Decorator Light Switch",
              brand: "BESTTEN",
              price: 17.79,
              unitPrice: 1.78,
              revenue: 17790,
              volume: 1000,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "112",
              name: "ENERLITES Toggle Light Switch, Single Pole, 15A 120V",
              brand: "ENERLITES Store",
              price: 9.99,
              unitPrice: 9.99,
              revenue: 14985,
              volume: 1500,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
            {
              id: "113",
              name: "Leviton 5601-2W 15 Amp, 120/277 Volt, Toggle Single-Pole AC Quiet Switch",
              brand: "Leviton",
              price: 3.52,
              unitPrice: 3.52,
              revenue: 14080,
              volume: 4000,
              url: "https://www.amazon.com/dp/B000U3BU0I",
            },
            {
              id: "114",
              name: "ELEGRP Matte White Single Pole Decorator Light Switch",
              brand: "ELEGRP",
              price: 16.99,
              unitPrice: 3.4,
              revenue: 13592,
              volume: 800,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "115",
              name: "Lutron Diva LED+ Dimmer Switch for Dimmable LED",
              brand: "Lutron",
              price: 17.43,
              unitPrice: 17.43,
              revenue: 13072.5,
              volume: 750,
              url: "https://www.amazon.com/dp/B00KLAXFQA",
            },
          ],
        },
      ],
      topProducts: [
        {
          category: "Dimmer Switches",
          products: [
            {
              id: "1",
              name: "Kasa Smart 3 Way Dimmer Switch KIT",
              brand: "Kasa",
              price: 42.99,
              unitPrice: 54.99,
              revenue: 85980,
              url: "https://www.amazon.com/dp/B0BC2MWTR9",
            },
            {
              id: "2",
              name: "Lutron Caseta Original Smart Dimmer Switch Kit",
              brand: "Lutron",
              price: 189.9,
              unitPrice: 94.95,
              revenue: 75960,
              url: "https://www.amazon.com/dp/B01M3XJUAD",
            },
            {
              id: "3",
              name: "ELEGRP Digital Dimmer Light Switch for 300W",
              brand: "ELEGRP",
              price: 59.99,
              unitPrice: 30.0,
              revenue: 59990,
              url: "https://www.amazon.com/dp/B099RJ2HRN",
            },
            {
              id: "4",
              name: "Kasa Smart Dimmer Switch HS220",
              brand: "Kasa",
              price: 19.98,
              unitPrice: 22.99,
              revenue: 59940,
              url: "https://www.amazon.com/dp/B079775ZZQ",
            },
            {
              id: "5",
              name: "Leviton SureSlide Dimmer Switch",
              brand: "Leviton",
              price: 14.07,
              unitPrice: 28.33,
              revenue: 56280,
              url: "https://www.amazon.com/dp/B0076HPM8A",
            },
            {
              id: "6",
              name: "ELEGRP Digital Dimmer Light Switch for 300W, 10 Pack",
              brand: "ELEGRP",
              price: 89.99,
              unitPrice: 9.0,
              revenue: 44995,
              url: "https://www.amazon.com/dp/B094XXG14N",
            },
            {
              id: "7",
              name: "Amico 6 Pack Dimmer Light Switch",
              brand: "GE",
              price: 44.99,
              unitPrice: 7.5,
              revenue: 40491,
              url: "https://www.amazon.com/dp/B0D3TBK88B",
            },
            {
              id: "8",
              name: "Lutron Ariadni/Toggler LED+ Dimmer Light Switch",
              brand: "Lutron",
              price: 19.47,
              unitPrice: 25.0,
              revenue: 38940,
              url: "https://www.amazon.com/dp/B006UTQCA2",
            },
            {
              id: "9",
              name: "Lutron Diva Smart Dimmer Switch for Caseta Smart Lighting",
              brand: "Lutron",
              price: 73.9,
              unitPrice: 52.99,
              revenue: 36950,
              url: "https://www.amazon.com/dp/B0BSHKS26L",
            },
            {
              id: "10",
              name: "Lutron Maestro LED+ Dual Dimmer and Switch",
              brand: "Lutron",
              price: 71.38,
              unitPrice: 50.0,
              revenue: 35690,
              url: "https://www.amazon.com/dp/B0CT3RFY6K",
            },
            {
              id: "11",
              name: "TP-Link Tapo Matter Smart Dimmer Switch",
              brand: "TP-Link",
              price: 24.99,
              unitPrice: 24.99,
              revenue: 29988,
              url: "https://www.amazon.com/dp/B0CBNX6Q51",
            },
            {
              id: "12",
              name: "Kasa Apple HomeKit Smart Dimmer Switch KS220P3",
              brand: "Kasa",
              price: 39.99,
              unitPrice: 39.99,
              revenue: 27993,
              url: "https://www.amazon.com/dp/B0BC2MWTR9",
            },
            {
              id: "13",
              name: "Lutron Diva Smart Dimmer Switch for Caseta Smart Lighting (2)",
              brand: "Lutron",
              price: 62.99,
              unitPrice: 31.5,
              revenue: 25196,
              url: "https://www.amazon.com/dp/B0BSHKS26L",
            },
            {
              id: "14",
              name: "TREATLIFE Smart Dimmer Switch 4 Pack",
              brand: "TREATLIFE",
              price: 65.99,
              unitPrice: 16.5,
              revenue: 23096.5,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "15",
              name: "Lutron Caseta Smart Lamp Dimmer 3-Way Kit and Pico Remote",
              brand: "Lutron",
              price: 59.95,
              unitPrice: 59.95,
              revenue: 20982.5,
              url: "https://www.amazon.com/dp/B00KLAXFQA",
            },
            {
              id: "16",
              name: "Leviton Decora Slide Dimmer Switch for Dimmable LED",
              brand: "Leviton",
              price: 19.99,
              unitPrice: 19.99,
              revenue: 19990,
              url: "https://www.amazon.com/dp/B0076HPM8A",
            },
            {
              id: "17",
              name: "TREATLIFE Dimmer Plug with 100FT Wireless Remote Control",
              brand: "TREATLIFE",
              price: 19.99,
              unitPrice: 19.99,
              revenue: 19990,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "18",
              name: "TP-Link Tapo Smart 3 Way Dimmer Switch KIT, Matter",
              brand: "TP-Link",
              price: 59.99,
              unitPrice: 59.99,
              revenue: 17997,
              url: "https://www.amazon.com/dp/B0CBNX6Q51",
            },
            {
              id: "19",
              name: "Leviton Decora Smart Dimmer Switch, Wi-Fi 2nd Gen",
              brand: "Leviton",
              price: 44.99,
              unitPrice: 44.99,
              revenue: 17996,
              url: "https://www.amazon.com/dp/B0076HPM8A",
            },
            {
              id: "20",
              name: "Philips Hue Smart Wireless Dimmer Switch V2",
              brand: "GE",
              price: 24.95,
              unitPrice: 24.95,
              revenue: 17465,
              url: "https://www.amazon.com/dp/B08W8GLPD5",
            },
          ],
        },
        {
          category: "Light Switches",
          products: [
            {
              id: "101",
              name: "Kasa Smart Light Switch HS200P3",
              brand: "Kasa",
              price: 42.99,
              unitPrice: 14.33,
              revenue: 128970,
              url: "https://www.amazon.com/dp/B07HGW8N7R",
            },
            {
              id: "102",
              name: "Kasa Smart Light Switch HS200",
              brand: "Kasa",
              price: 16.99,
              unitPrice: 19.99,
              revenue: 84950,
              url: "https://www.amazon.com/dp/B01EZV35QU",
            },
            {
              id: "103",
              name: "Lutron Caseta 3 Way Smart Dimmer Switch Kit",
              brand: "Lutron",
              price: 69.95,
              unitPrice: 69.95,
              revenue: 69950,
              url: "https://www.amazon.com/dp/B07HM6L48C",
            },
            {
              id: "104",
              name: "Kasa Smart 3 Way Switch HS210 KIT",
              brand: "Kasa",
              price: 33.99,
              unitPrice: 17.0,
              revenue: 67980,
              url: "https://www.amazon.com/dp/B07724HNTX",
            },
            {
              id: "105",
              name: "Philips Hue Smart Dimmer Switch with Remote",
              brand: "GE",
              price: 22.49,
              unitPrice: 3.98,
              revenue: 44980,
              url: "https://www.amazon.com/dp/B08W8GLPD5",
            },
            {
              id: "106",
              name: "Kasa Smart Switch 2-Gang HS200-2",
              brand: "Kasa",
              price: 31.99,
              unitPrice: 31.99,
              revenue: 31990,
              url: "https://www.amazon.com/dp/B0D3KP68S7",
            },
            {
              id: "107",
              name: "Lutron Caseta Original Smart Switch",
              brand: "Lutron",
              price: 59.95,
              unitPrice: 59.95,
              revenue: 29975,
              url: "https://www.amazon.com/dp/B017LRCG38",
            },
            {
              id: "108",
              name: "Leviton E5601-MW Decora Edge 15 Amp Single Pole Rocker Switch",
              brand: "Leviton",
              price: 25.98,
              unitPrice: 2.6,
              revenue: 25980,
              url: "https://www.amazon.com/dp/B0C86MJLVH",
            },
            {
              id: "109",
              name: "TP-Link Tapo Matter Smart Light Switch",
              brand: "TP-Link",
              price: 24.99,
              unitPrice: 24.99,
              revenue: 24990,
              url: "https://www.amazon.com/dp/B0CBNX6Q51",
            },
            {
              id: "110",
              name: "Amico 30 Pack Single Pole Light Switch with Wall Plate",
              brand: "Other",
              price: 49.99,
              unitPrice: 1.67,
              revenue: 19996,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
            {
              id: "111",
              name: "BESTTEN 10 Pack Single Pole Decorator Light Switch",
              brand: "BESTTEN",
              price: 17.79,
              unitPrice: 1.78,
              revenue: 17790,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "112",
              name: "ENERLITES Toggle Light Switch, Single Pole, 15A 120V",
              brand: "ENERLITES Store",
              price: 9.99,
              unitPrice: 9.99,
              revenue: 14985,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
            {
              id: "113",
              name: "Leviton 5601-2W 15 Amp, 120/277 Volt, Toggle Single-Pole AC Quiet Switch",
              brand: "Leviton",
              price: 3.52,
              unitPrice: 3.52,
              revenue: 14080,
              url: "https://www.amazon.com/dp/B000U3BU0I",
            },
            {
              id: "114",
              name: "ELEGRP Matte White Single Pole Decorator Light Switch",
              brand: "ELEGRP",
              price: 16.99,
              unitPrice: 3.4,
              revenue: 13592,
              url: "https://www.amazon.com/dp/B07YWVLBG7",
            },
            {
              id: "115",
              name: "Lutron Diva LED+ Dimmer Switch for Dimmable LED",
              brand: "Lutron",
              price: 17.43,
              unitPrice: 17.43,
              revenue: 13072.5,
              url: "https://www.amazon.com/dp/B00KLAXFQA",
            },
            {
              id: "116",
              name: "Leviton E5603-MW Decora Edge 15 Amp 3-Way Rocker Switch",
              brand: "Leviton",
              price: 7.53,
              unitPrice: 7.53,
              revenue: 11295,
              url: "https://www.amazon.com/dp/B000U3BU0I",
            },
            {
              id: "117",
              name: "AIDA 20 Pack Light Switch Single Pole Light Switch",
              brand: "Other",
              price: 15.09,
              unitPrice: 0.75,
              revenue: 11317.5,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
            {
              id: "118",
              name: "ENERLITES Toggle Light Switch, Single Pole, 15A 120V (10 Pack)",
              brand: "ENERLITES Store",
              price: 17.99,
              unitPrice: 1.8,
              revenue: 10794,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
            {
              id: "119",
              name: "(50 Pack) CML Decorator Wall Light Switch, Single Pole",
              brand: "Other",
              price: 37.99,
              unitPrice: 0.76,
              revenue: 9497.5,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
            {
              id: "120",
              name: "ENERLITES Toggle Light Switch, Single Pole, 15A 120V (20 Pack)",
              brand: "ENERLITES Store",
              price: 29.98,
              unitPrice: 1.5,
              revenue: 8994,
              url: "https://www.amazon.com/dp/B0DCZCVRL8",
            },
          ],
        },
      ],
    },
    pricingAnalysis: {
      priceDistribution: [
        {
          category: "Dimmer Switches",
          skuPrices: [
            19.99, 59.99, 14.07, 89.99, 42.99, 16.99, 44.99, 62.99, 24.95, 19.98, 19.47, 38.96, 56.76, 62.99, 11.99,
            39.99, 15.32, 629.55, 12.99, 65.99, 73.9, 71.38, 24.99, 39.99, 65.99, 59.95, 19.99, 19.99, 59.99, 44.99,
            24.95,
          ],
          unitPrices: [
            19.99, 30.0, 28.33, 9.0, 54.99, 8.5, 7.5, 10.5, 27.24, 22.99, 25.0, 38.96, 28.38, 21.0, 17.06, 6.67, 15.32,
            69.95, 12.99, 16.5, 52.99, 50.0, 24.99, 39.99, 16.5, 59.95, 19.99, 19.99, 59.99, 44.99, 24.95,
          ],
          stats: {
            sku: {
              min: 8.99,
              q1: 19.98,
              median: 34.18,
              mean: 44.37,
              q3: 52.99,
              max: 629.55,
            },
            unit: {
              min: 6.67,
              q1: 17.06,
              median: 25.0,
              mean: 28.45,
              q3: 39.99,
              max: 69.95,
            },
          },
        },
        {
          category: "Light Switches",
          skuPrices: [
            6.74, 9.99, 19.99, 37.99, 43.99, 41.9, 8.39, 64.95, 13.99, 11.2, 39.99, 9.89, 13.99, 29.98, 3.75, 13.9,
            18.99, 9.99, 17.43, 15.09, 42.99, 16.99, 69.95, 33.99, 22.49, 31.99, 59.95, 25.98, 24.99, 49.99, 17.79,
            9.99, 3.52, 16.99, 17.43, 7.53, 15.09, 17.99, 37.99, 29.98,
          ],
          unitPrices: [
            7.19, 9.99, 19.99, 9.5, 51.99, 41.9, 2.38, 64.95, 17.99, 11.2, 10.0, 9.89, 7.0, 44.98, 8.86, 19.87, 9.5,
            9.99, 17.43, 16.99, 14.33, 19.99, 69.95, 17.0, 3.98, 31.99, 59.95, 2.6, 24.99, 1.67, 1.78, 9.99, 3.52, 3.4,
            17.43, 7.53, 0.75, 1.8, 0.76, 1.5,
          ],
          stats: {
            sku: {
              min: 2.68,
              q1: 9.99,
              median: 16.99,
              mean: 21.61,
              q3: 28.41,
              max: 85.99,
            },
            unit: {
              min: 0.75,
              q1: 3.52,
              median: 9.99,
              mean: 14.23,
              q3: 17.43,
              max: 69.95,
            },
          },
        },
      ],
      brandPriceDistribution: [
        {
          category: "Dimmer Switches",
          brands: [
            {
              name: "Lutron",
              skuPrices: [
                19.47, 56.76, 629.55, 23.28, 18.95, 57.95, 23.52, 52.99, 189.9, 39.95, 73.9, 71.38, 62.99, 59.95,
              ],
              unitPrices: [
                25.0, 28.38, 69.95, 25.97, 21.27, 57.95, 32.97, 52.99, 94.95, 50.0, 52.99, 50.0, 31.5, 59.95,
              ],
            },
            {
              name: "Kasa",
              skuPrices: [42.99, 19.98, 62.99, 39.99],
              unitPrices: [54.99, 22.99, 21.0, 39.99],
            },
            {
              name: "Leviton",
              skuPrices: [14.07, 24.95, 38.96, 19.99, 44.99],
              unitPrices: [28.33, 27.24, 38.96, 19.99, 44.99],
            },
            {
              name: "GE",
              skuPrices: [44.99, 15.32, 14.99, 24.95],
              unitPrices: [7.5, 15.32, 14.99, 24.95],
            },
            {
              name: "ELEGRP",
              skuPrices: [59.99, 89.99, 62.99],
              unitPrices: [30.0, 9.0, 10.5],
            },
            {
              name: "BESTTEN",
              skuPrices: [38.96, 65.99],
              unitPrices: [38.96, 16.5],
            },
            {
              name: "TREATLIFE",
              skuPrices: [65.99, 19.99],
              unitPrices: [16.5, 19.99],
            },
            {
              name: "TP-Link",
              skuPrices: [24.99, 59.99],
              unitPrices: [24.99, 59.99],
            },
          ],
        },
        {
          category: "Light Switches",
          brands: [
            {
              name: "Leviton",
              skuPrices: [11.2, 13.9, 25.98, 3.52, 7.53, 11.45, 2.68, 7.8, 11.92, 9.44],
              unitPrices: [11.2, 19.87, 2.6, 3.52, 7.53, 11.45, 8.37, 8.93, 11.92, 16.4],
            },
            {
              name: "Kasa",
              skuPrices: [42.99, 16.99, 33.99, 31.99],
              unitPrices: [14.33, 19.99, 17.0, 31.99],
            },
            {
              name: "Lutron",
              skuPrices: [64.95, 17.43, 69.95, 59.95],
              unitPrices: [64.95, 17.43, 69.95, 59.95],
            },
            {
              name: "GE",
              skuPrices: [13.99, 8.99, 11.74, 22.49],
              unitPrices: [17.99, 8.99, 2.35, 3.98],
            },
            {
              name: "ELEGRP",
              skuPrices: [31.99, 17.79, 16.99],
              unitPrices: [3.2, 17.79, 3.4],
            },
            {
              name: "BESTTEN",
              skuPrices: [17.79, 37.99],
              unitPrices: [1.78, 0.76],
            },
            {
              name: "ENERLITES Store",
              skuPrices: [9.99, 17.99, 29.98],
              unitPrices: [9.99, 1.8, 1.5],
            },
            {
              name: "TP-Link",
              skuPrices: [24.99],
              unitPrices: [24.99],
            },
            {
              name: "Other",
              skuPrices: [49.99, 15.09, 37.99],
              unitPrices: [1.67, 0.75, 0.76],
            },
          ],
        },
      ],
    },
    marketInsights: {
      smartVsTraditional: [
        { category: "Dimmer Switches", smart: 642716.5, traditional: 612351.5 },
        { category: "Light Switches", smart: 608479, traditional: 383404.5 },
      ],
    },
    summaryMetrics: {
      priceRange: "$2.68 - $629.55",
      avgVolumePerProduct: 346.54,
      medianPrice: 22.97,
      majorBrands: 4,
    },
  }
}
