// Auto-generated from combined_products_with_final_categories.csv
// Generated on 2025-06-09 18:45:10
// Source: Amazon scraped data (filtered: source=amazon, product_segment!=OUT_OF_SCOPE)

export async function fetchDashboardData() {
  return {
    executiveSummary: {
      "totalProducts": 288,
      "totalSalesVolume": 80750,
      "averagePrice": 32.37,
      "totalBrands": 59,
      "marketLeader": "Kasa",
      "marketLeaderShare": 20.8,
      "marketLeaderProducts": 8,
      "productDistribution": [
            {
                  "name": "Light Switches",
                  "value": 137
            },
            {
                  "name": "Dimmer Switches",
                  "value": 151
            }
      ]
},
    brandAnalysis: {
      brandCategoryRevenue: [
        {
                "brand": "Lutron",
                "dimmerRevenue": 472136,
                "switchRevenue": 37958
        },
        {
                "brand": "Kasa",
                "dimmerRevenue": 184012,
                "switchRevenue": 313890
        },
        {
                "brand": "Leviton",
                "dimmerRevenue": 133730,
                "switchRevenue": 138014
        },
        {
                "brand": "ELEGRP",
                "dimmerRevenue": 130329,
                "switchRevenue": 37811
        },
        {
                "brand": "GE",
                "dimmerRevenue": 121839,
                "switchRevenue": 40035
        },
        {
                "brand": "BESTTEN",
                "dimmerRevenue": 48181,
                "switchRevenue": 38582
        },
        {
                "brand": "TP-Link",
                "dimmerRevenue": 60289,
                "switchRevenue": 24990
        },
        {
                "brand": "TREATLIFE",
                "dimmerRevenue": 65132,
                "switchRevenue": 8998
        },
        {
                "brand": "Amazon",
                "dimmerRevenue": 24977,
                "switchRevenue": 24084
        },
        {
                "brand": "ENERLITES Store",
                "dimmerRevenue": 0,
                "switchRevenue": 44973
        }
]
    },
    productAnalysis: {
      priceVsRevenue: [
        {
          category: "Dimmer Switches",
          products: [
            {
                        "id": "1",
                        "name": "Kasa Smart 3 Way Dimmer Switch KIT, Dimmable Light Switch Compatible with Alexa, Google Assistant and SmartThings, Neutral Wire Needed, 2.4GHz, ETL Certified, No Hub Required, White (KS230 KIT v2)",
                        "brand": "Kasa",
                        "price": 42.99,
                        "unitPrice": 42.99,
                        "revenue": 85980,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B0BC2MWTR9"
            },
            {
                        "id": "2",
                        "name": "Lutron Caseta Original Smart Dimmer Switch Kit, 2 Dimmer Switches, 2 Wall Plates, 2 Pico Remotes, and Smart Hub, Works with Alexa, Apple Home, Google Home, 3 Way, 150W, No Neutral, P-BDG-PKG2W-A",
                        "brand": "Lutron",
                        "price": 189.9,
                        "unitPrice": 94.95,
                        "revenue": 75960,
                        "volume": 400,
                        "url": "https://www.amazon.com/dp/B01M3XJUAD"
            },
            {
                        "id": "3",
                        "name": "Lutron Caseta 3 Way Smart Dimmer Switch Kit, w/ Wireless 3 way Pico Remote and Bracket, Light Switch for LED Lights, No Neutral Required, P-PKG1WB-WH",
                        "brand": "Lutron",
                        "price": 69.95,
                        "unitPrice": 69.95,
                        "revenue": 69950,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B07HM6L48C"
            },
            {
                        "id": "4",
                        "name": "ELEGRP Digital Dimmer Light Switch for 300W Dimmable LED/CFL Lights and 600W Incandescent/Halogen, Single Pole/3-Way LED Slide Dimmer, Wall Plate Included, UL Listed, 6 Pack, Matte White",
                        "brand": "ELEGRP",
                        "price": 59.99,
                        "unitPrice": 30.0,
                        "revenue": 59990,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B099RJ2HRN"
            },
            {
                        "id": "5",
                        "name": "Kasa Smart Dimmer Switch HS220, Single Pole, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch Works with Alexa and Google Home, UL Certified, No Hub Required, 1 Pack",
                        "brand": "Kasa",
                        "price": 19.98,
                        "unitPrice": 19.98,
                        "revenue": 59940,
                        "volume": 3000,
                        "url": "https://www.amazon.com/dp/B079775ZZQ"
            },
            {
                        "id": "6",
                        "name": "Leviton SureSlide Dimmer Switch for Dimmable LED, Halogen and Incandescent Bulbs, 6674-P0W, White",
                        "brand": "Leviton",
                        "price": 14.07,
                        "unitPrice": 14.07,
                        "revenue": 56280,
                        "volume": 4000,
                        "url": "https://www.amazon.com/dp/B0076HPM8A"
            },
            {
                        "id": "7",
                        "name": "ELEGRP Digital Dimmer Light Switch for 300W Dimmable LED/CFL Lights and 600W Incandescent/Halogen, Single Pole/3-Way LED Slide Dimmer Light Switch, Wall Plate Included, UL Listed, 10 Pack, Matte White",
                        "brand": "ELEGRP",
                        "price": 89.99,
                        "unitPrice": 9.0,
                        "revenue": 44995,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B094XXG14N"
            },
            {
                        "id": "8",
                        "name": "Philips Hue Smart Dimmer Switch with Remote, White - 1 Pack - Turns Hue Lights On, Off, Dims or Brightens - Requires Hue Bridge - Easy, No-Wire Installation",
                        "brand": "GE",
                        "price": 22.49,
                        "unitPrice": 3.98,
                        "revenue": 44980,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B08W8GLPD5"
            },
            {
                        "id": "9",
                        "name": "Amico 6 Pack Dimmer Light Switch, Single-Pole or 3-Way Slide Dimmer Switches for Led Lights, Suitable for 150W Dimmable LED/CFL Lights and 600W Incandescent/Halogen, Wall Plate Included, White",
                        "brand": "GE",
                        "price": 44.99,
                        "unitPrice": 7.5,
                        "revenue": 40491,
                        "volume": 900,
                        "url": "https://www.amazon.com/dp/B0D3TBK88B"
            },
            {
                        "id": "10",
                        "name": "Lutron Ariadni/Toggler LED+ Dimmer Light Switch for Dimmable LED, Halogen and Incandescent Dimmer Switch, 150W, Single-Pole/3-Way, AYCL-153P-WH, White",
                        "brand": "Lutron",
                        "price": 19.47,
                        "unitPrice": 19.47,
                        "revenue": 38940,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B006UTQCA2"
            },
            {
                        "id": "11",
                        "name": "Lutron Diva Smart Dimmer Switch for Caseta Smart Lighting (Lutron Smart Hub Required) w/ Wall Plate, for LED Lights, 150 Watt, Single-Pole/3Way, No Neutral Required, DVRFW-6L-WH-A, White",
                        "brand": "Lutron",
                        "price": 73.9,
                        "unitPrice": 73.9,
                        "revenue": 36950,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0BSHKS26L"
            },
            {
                        "id": "12",
                        "name": "Lutron Maestro LED+ Dual Dimmer and Switch | 75-Watt LED Bulbs/2.5A Fans, Single-Pole | MACL-L3S25-WH | White",
                        "brand": "Lutron",
                        "price": 71.38,
                        "unitPrice": 71.38,
                        "revenue": 35690,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0CT3RFY6K"
            },
            {
                        "id": "13",
                        "name": "TP-Link Tapo Matter Smart Dimmer Switch, Single Pole, Neutral Wiring & 2.4 GHz WiFi Required, Compatible with Alexa, Siri, Google Home, Bixby, UL Certified Light Switch, (4-Pack)",
                        "brand": "TP-Link",
                        "price": 65.99,
                        "unitPrice": 16.5,
                        "revenue": 32995,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0DRZ77JQT"
            },
            {
                        "id": "14",
                        "name": "Kasa Apple HomeKit Smart Dimmer Switch KS220P3, Single Pole, Neutral Wire Required,2.4GHz Wi-Fi Light Works with Siri, Alexa and Google Home,UL Certified, No Hub Required,White, 3 Count (Pack of 1)",
                        "brand": "Kasa",
                        "price": 62.99,
                        "unitPrice": 21.0,
                        "revenue": 31495,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0BTMWZH3K"
            },
            {
                        "id": "15",
                        "name": "Lutron Diva Smart Dimmer Switch for Caseta Smart Lighting (Lutron Smart Hub Required), for LED Lights, 150 Watt, Single-Pole/3Way, No Neutral Required, DVRF-6LS-WH-9, White, 9 Pack",
                        "brand": "Lutron",
                        "price": 629.55,
                        "unitPrice": 69.95,
                        "revenue": 31477,
                        "volume": 50,
                        "url": "https://www.amazon.com/dp/B0C7LTX71C"
            }
]
        },
        {
          category: "Light Switches", 
          products: [
            {
                        "id": "1",
                        "name": "Kasa Smart Light Switch HS200P3, Single Pole, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch Works with Alexa and Google Home, UL Certified, No Hub Required, 3 Count -Pack of 1 , White",
                        "brand": "Kasa",
                        "price": 42.99,
                        "unitPrice": 14.33,
                        "revenue": 128970,
                        "volume": 3000,
                        "url": "https://www.amazon.com/dp/B07HGW8N7R"
            },
            {
                        "id": "2",
                        "name": "Kasa Smart Light Switch HS200, Single Pole, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch Works with Alexa and Google Home, UL Certified, No Hub Required , White, HS200",
                        "brand": "Kasa",
                        "price": 16.99,
                        "unitPrice": 16.99,
                        "revenue": 84949,
                        "volume": 5000,
                        "url": "https://www.amazon.com/dp/B01EZV35QU"
            },
            {
                        "id": "3",
                        "name": "Kasa Smart 3 Way Switch HS210 KIT, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch works with Alexa and Google Home, UL Certified, No Hub Required, White,2 Count (Pack of 1)",
                        "brand": "Kasa",
                        "price": 33.99,
                        "unitPrice": 17.0,
                        "revenue": 67980,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B07724HNTX"
            },
            {
                        "id": "4",
                        "name": "Kasa Smart Switch 2-Gang HS200-2, Single Pole,Neutral Wire Required, 2.4GHz Wi-Fi Light Switch Compatible with Alexa and Google Home, UL Certified, No Hub Required, White",
                        "brand": "Kasa",
                        "price": 31.99,
                        "unitPrice": 31.99,
                        "revenue": 31990,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B0D3KP68S7"
            },
            {
                        "id": "5",
                        "name": "Lutron Caseta Original Smart Switch (Lutron Smart Hub Required), for LED Lights and Fans, 6 Amp, Single-Pole/3-Way, Neutral Required, PD-6ANS-WH, White",
                        "brand": "Lutron",
                        "price": 59.95,
                        "unitPrice": 59.95,
                        "revenue": 29975,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B017LRCG38"
            },
            {
                        "id": "6",
                        "name": "Leviton E5601-MW Decora Edge 15 Amp Single Pole Rocker Switch, 10-Pack, White",
                        "brand": "Leviton",
                        "price": 25.98,
                        "unitPrice": 2.6,
                        "revenue": 25980,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B0C86MJLVH"
            },
            {
                        "id": "7",
                        "name": "TP-Link Tapo Matter Smart Light Switch: Voice Control w/Siri, Alexa & Google Home | UL Certified | Timer & Schedule | Easy Guided Install | Neutral Wire Required | Single Pole | Tapo S505(2-Pack)",
                        "brand": "TP-Link",
                        "price": 24.99,
                        "unitPrice": 12.5,
                        "revenue": 24990,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B0CBNX6Q51"
            },
            {
                        "id": "8",
                        "name": "Amico 30 Pack Single Pole Light Switch with Wall Plate, UL Listed, 15A 120/277V, On/Off Rocker Paddle Interrupter Wall Switch, Grounding Screw, Residential Grade, Suitable for Home and Business, White",
                        "brand": "Amico",
                        "price": 49.99,
                        "unitPrice": 1.67,
                        "revenue": 19996,
                        "volume": 400,
                        "url": "https://www.amazon.com/dp/B0DCZCVRL8"
            },
            {
                        "id": "9",
                        "name": "Leviton E5603-MW Decora Edge 15 Amp 3-Way Rocker Switch, 10-Pack, White",
                        "brand": "Leviton",
                        "price": 37.98,
                        "unitPrice": 3.7979999999999996,
                        "revenue": 18990,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0C86LDZLW"
            },
            {
                        "id": "10",
                        "name": "Leviton Decora Smart Switch, Wi-Fi 2nd Gen, Neutral Wire Required, Works with Matter, My Leviton, Alexa, Google Assistant, Apple Home/Siri & Wired or Wire-Free 3-Way, D215S-1RW, White",
                        "brand": "Leviton",
                        "price": 37.84,
                        "unitPrice": 37.84,
                        "revenue": 18920,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0BVKZLT3B"
            },
            {
                        "id": "11",
                        "name": "BESTTEN 10 Pack Single Pole Decorator Light Switch with Wallplate, 15A 120/277V, Rocker Paddle Wall Switch, On/Off Interrupter for LED and Other Lamps, UL Listed, White",
                        "brand": "BESTTEN",
                        "price": 17.69,
                        "unitPrice": 1.77,
                        "revenue": 17690,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B01MRXOXWB"
            },
            {
                        "id": "12",
                        "name": "AIDA 20 Pack Light Switch Single Pole Light Switch Square Rocker Switch Decora Switches White, 15 Amp Self-grounding Electrical Light Switches, Residential Grade, UL Listed Glossy White",
                        "brand": "AIDA",
                        "price": 34.99,
                        "unitPrice": 1.7495,
                        "revenue": 17495,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B09CKT5B9C"
            },
            {
                        "id": "13",
                        "name": "ENERLITES Decorator Paddle Rocker Light Switch, Gloss Finish, Single Pole, 3 Wire, Grounding Screw, Residential Grade, 15A 120V/277V, UL Listed, 91150-W-10PCS, White (10 Pack)",
                        "brand": "ENERLITES Store",
                        "price": 17.99,
                        "unitPrice": 1.8,
                        "revenue": 16190,
                        "volume": 900,
                        "url": "https://www.amazon.com/dp/B00QXOSTFU"
            },
            {
                        "id": "14",
                        "name": "ELEGRP Matte White Single Pole Decorator Light Switch 15Amp, 120-277V, Paddle Rocker Replacement, On/Off Wall Switch, Self-Grounding, Residential Grade, w/Wall Plate, UL/CUL (10 Pack)",
                        "brand": "ELEGRP",
                        "price": 31.99,
                        "unitPrice": 3.2,
                        "revenue": 15995,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B09MW38VK7"
            },
            {
                        "id": "15",
                        "name": "Amazon Basics Smart Switch, Single Pole, Works with Alexa Only, 2.4 GHz Wi-Fi, No Hub Required, White",
                        "brand": "Amazon",
                        "price": 15.09,
                        "unitPrice": 15.09,
                        "revenue": 15090,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B095X911T8"
            }
]
        }
      ],
      topProducts: [
        {
          category: "Dimmer Switches",
          products: [
            {
                        "id": "1",
                        "name": "Kasa Smart 3 Way Dimmer Switch KIT, Dimmable Light Switch Compatible with Alexa, Google Assistant and SmartThings, Neutral Wire Needed, 2.4GHz, ETL Certified, No Hub Required, White (KS230 KIT v2)",
                        "brand": "Kasa",
                        "price": 42.99,
                        "unitPrice": 42.99,
                        "revenue": 85980,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B0BC2MWTR9"
            },
            {
                        "id": "2",
                        "name": "Lutron Caseta Original Smart Dimmer Switch Kit, 2 Dimmer Switches, 2 Wall Plates, 2 Pico Remotes, and Smart Hub, Works with Alexa, Apple Home, Google Home, 3 Way, 150W, No Neutral, P-BDG-PKG2W-A",
                        "brand": "Lutron",
                        "price": 189.9,
                        "unitPrice": 94.95,
                        "revenue": 75960,
                        "volume": 400,
                        "url": "https://www.amazon.com/dp/B01M3XJUAD"
            },
            {
                        "id": "3",
                        "name": "Lutron Caseta 3 Way Smart Dimmer Switch Kit, w/ Wireless 3 way Pico Remote and Bracket, Light Switch for LED Lights, No Neutral Required, P-PKG1WB-WH",
                        "brand": "Lutron",
                        "price": 69.95,
                        "unitPrice": 69.95,
                        "revenue": 69950,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B07HM6L48C"
            },
            {
                        "id": "4",
                        "name": "ELEGRP Digital Dimmer Light Switch for 300W Dimmable LED/CFL Lights and 600W Incandescent/Halogen, Single Pole/3-Way LED Slide Dimmer, Wall Plate Included, UL Listed, 6 Pack, Matte White",
                        "brand": "ELEGRP",
                        "price": 59.99,
                        "unitPrice": 30.0,
                        "revenue": 59990,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B099RJ2HRN"
            },
            {
                        "id": "5",
                        "name": "Kasa Smart Dimmer Switch HS220, Single Pole, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch Works with Alexa and Google Home, UL Certified, No Hub Required, 1 Pack",
                        "brand": "Kasa",
                        "price": 19.98,
                        "unitPrice": 19.98,
                        "revenue": 59940,
                        "volume": 3000,
                        "url": "https://www.amazon.com/dp/B079775ZZQ"
            },
            {
                        "id": "6",
                        "name": "Leviton SureSlide Dimmer Switch for Dimmable LED, Halogen and Incandescent Bulbs, 6674-P0W, White",
                        "brand": "Leviton",
                        "price": 14.07,
                        "unitPrice": 14.07,
                        "revenue": 56280,
                        "volume": 4000,
                        "url": "https://www.amazon.com/dp/B0076HPM8A"
            },
            {
                        "id": "7",
                        "name": "ELEGRP Digital Dimmer Light Switch for 300W Dimmable LED/CFL Lights and 600W Incandescent/Halogen, Single Pole/3-Way LED Slide Dimmer Light Switch, Wall Plate Included, UL Listed, 10 Pack, Matte White",
                        "brand": "ELEGRP",
                        "price": 89.99,
                        "unitPrice": 9.0,
                        "revenue": 44995,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B094XXG14N"
            },
            {
                        "id": "8",
                        "name": "Philips Hue Smart Dimmer Switch with Remote, White - 1 Pack - Turns Hue Lights On, Off, Dims or Brightens - Requires Hue Bridge - Easy, No-Wire Installation",
                        "brand": "GE",
                        "price": 22.49,
                        "unitPrice": 3.98,
                        "revenue": 44980,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B08W8GLPD5"
            },
            {
                        "id": "9",
                        "name": "Amico 6 Pack Dimmer Light Switch, Single-Pole or 3-Way Slide Dimmer Switches for Led Lights, Suitable for 150W Dimmable LED/CFL Lights and 600W Incandescent/Halogen, Wall Plate Included, White",
                        "brand": "GE",
                        "price": 44.99,
                        "unitPrice": 7.5,
                        "revenue": 40491,
                        "volume": 900,
                        "url": "https://www.amazon.com/dp/B0D3TBK88B"
            },
            {
                        "id": "10",
                        "name": "Lutron Ariadni/Toggler LED+ Dimmer Light Switch for Dimmable LED, Halogen and Incandescent Dimmer Switch, 150W, Single-Pole/3-Way, AYCL-153P-WH, White",
                        "brand": "Lutron",
                        "price": 19.47,
                        "unitPrice": 19.47,
                        "revenue": 38940,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B006UTQCA2"
            },
            {
                        "id": "11",
                        "name": "Lutron Diva Smart Dimmer Switch for Caseta Smart Lighting (Lutron Smart Hub Required) w/ Wall Plate, for LED Lights, 150 Watt, Single-Pole/3Way, No Neutral Required, DVRFW-6L-WH-A, White",
                        "brand": "Lutron",
                        "price": 73.9,
                        "unitPrice": 73.9,
                        "revenue": 36950,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0BSHKS26L"
            },
            {
                        "id": "12",
                        "name": "Lutron Maestro LED+ Dual Dimmer and Switch | 75-Watt LED Bulbs/2.5A Fans, Single-Pole | MACL-L3S25-WH | White",
                        "brand": "Lutron",
                        "price": 71.38,
                        "unitPrice": 71.38,
                        "revenue": 35690,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0CT3RFY6K"
            },
            {
                        "id": "13",
                        "name": "TP-Link Tapo Matter Smart Dimmer Switch, Single Pole, Neutral Wiring & 2.4 GHz WiFi Required, Compatible with Alexa, Siri, Google Home, Bixby, UL Certified Light Switch, (4-Pack)",
                        "brand": "TP-Link",
                        "price": 65.99,
                        "unitPrice": 16.5,
                        "revenue": 32995,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0DRZ77JQT"
            },
            {
                        "id": "14",
                        "name": "Kasa Apple HomeKit Smart Dimmer Switch KS220P3, Single Pole, Neutral Wire Required,2.4GHz Wi-Fi Light Works with Siri, Alexa and Google Home,UL Certified, No Hub Required,White, 3 Count (Pack of 1)",
                        "brand": "Kasa",
                        "price": 62.99,
                        "unitPrice": 21.0,
                        "revenue": 31495,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0BTMWZH3K"
            },
            {
                        "id": "15",
                        "name": "Lutron Diva Smart Dimmer Switch for Caseta Smart Lighting (Lutron Smart Hub Required), for LED Lights, 150 Watt, Single-Pole/3Way, No Neutral Required, DVRF-6LS-WH-9, White, 9 Pack",
                        "brand": "Lutron",
                        "price": 629.55,
                        "unitPrice": 69.95,
                        "revenue": 31477,
                        "volume": 50,
                        "url": "https://www.amazon.com/dp/B0C7LTX71C"
            }
]
        },
        {
          category: "Light Switches", 
          products: [
            {
                        "id": "1",
                        "name": "Kasa Smart Light Switch HS200P3, Single Pole, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch Works with Alexa and Google Home, UL Certified, No Hub Required, 3 Count -Pack of 1 , White",
                        "brand": "Kasa",
                        "price": 42.99,
                        "unitPrice": 14.33,
                        "revenue": 128970,
                        "volume": 3000,
                        "url": "https://www.amazon.com/dp/B07HGW8N7R"
            },
            {
                        "id": "2",
                        "name": "Kasa Smart Light Switch HS200, Single Pole, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch Works with Alexa and Google Home, UL Certified, No Hub Required , White, HS200",
                        "brand": "Kasa",
                        "price": 16.99,
                        "unitPrice": 16.99,
                        "revenue": 84949,
                        "volume": 5000,
                        "url": "https://www.amazon.com/dp/B01EZV35QU"
            },
            {
                        "id": "3",
                        "name": "Kasa Smart 3 Way Switch HS210 KIT, Needs Neutral Wire, 2.4GHz Wi-Fi Light Switch works with Alexa and Google Home, UL Certified, No Hub Required, White,2 Count (Pack of 1)",
                        "brand": "Kasa",
                        "price": 33.99,
                        "unitPrice": 17.0,
                        "revenue": 67980,
                        "volume": 2000,
                        "url": "https://www.amazon.com/dp/B07724HNTX"
            },
            {
                        "id": "4",
                        "name": "Kasa Smart Switch 2-Gang HS200-2, Single Pole,Neutral Wire Required, 2.4GHz Wi-Fi Light Switch Compatible with Alexa and Google Home, UL Certified, No Hub Required, White",
                        "brand": "Kasa",
                        "price": 31.99,
                        "unitPrice": 31.99,
                        "revenue": 31990,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B0D3KP68S7"
            },
            {
                        "id": "5",
                        "name": "Lutron Caseta Original Smart Switch (Lutron Smart Hub Required), for LED Lights and Fans, 6 Amp, Single-Pole/3-Way, Neutral Required, PD-6ANS-WH, White",
                        "brand": "Lutron",
                        "price": 59.95,
                        "unitPrice": 59.95,
                        "revenue": 29975,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B017LRCG38"
            },
            {
                        "id": "6",
                        "name": "Leviton E5601-MW Decora Edge 15 Amp Single Pole Rocker Switch, 10-Pack, White",
                        "brand": "Leviton",
                        "price": 25.98,
                        "unitPrice": 2.6,
                        "revenue": 25980,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B0C86MJLVH"
            },
            {
                        "id": "7",
                        "name": "TP-Link Tapo Matter Smart Light Switch: Voice Control w/Siri, Alexa & Google Home | UL Certified | Timer & Schedule | Easy Guided Install | Neutral Wire Required | Single Pole | Tapo S505(2-Pack)",
                        "brand": "TP-Link",
                        "price": 24.99,
                        "unitPrice": 12.5,
                        "revenue": 24990,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B0CBNX6Q51"
            },
            {
                        "id": "8",
                        "name": "Amico 30 Pack Single Pole Light Switch with Wall Plate, UL Listed, 15A 120/277V, On/Off Rocker Paddle Interrupter Wall Switch, Grounding Screw, Residential Grade, Suitable for Home and Business, White",
                        "brand": "Amico",
                        "price": 49.99,
                        "unitPrice": 1.67,
                        "revenue": 19996,
                        "volume": 400,
                        "url": "https://www.amazon.com/dp/B0DCZCVRL8"
            },
            {
                        "id": "9",
                        "name": "Leviton E5603-MW Decora Edge 15 Amp 3-Way Rocker Switch, 10-Pack, White",
                        "brand": "Leviton",
                        "price": 37.98,
                        "unitPrice": 3.7979999999999996,
                        "revenue": 18990,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0C86LDZLW"
            },
            {
                        "id": "10",
                        "name": "Leviton Decora Smart Switch, Wi-Fi 2nd Gen, Neutral Wire Required, Works with Matter, My Leviton, Alexa, Google Assistant, Apple Home/Siri & Wired or Wire-Free 3-Way, D215S-1RW, White",
                        "brand": "Leviton",
                        "price": 37.84,
                        "unitPrice": 37.84,
                        "revenue": 18920,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B0BVKZLT3B"
            },
            {
                        "id": "11",
                        "name": "BESTTEN 10 Pack Single Pole Decorator Light Switch with Wallplate, 15A 120/277V, Rocker Paddle Wall Switch, On/Off Interrupter for LED and Other Lamps, UL Listed, White",
                        "brand": "BESTTEN",
                        "price": 17.69,
                        "unitPrice": 1.77,
                        "revenue": 17690,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B01MRXOXWB"
            },
            {
                        "id": "12",
                        "name": "AIDA 20 Pack Light Switch Single Pole Light Switch Square Rocker Switch Decora Switches White, 15 Amp Self-grounding Electrical Light Switches, Residential Grade, UL Listed Glossy White",
                        "brand": "AIDA",
                        "price": 34.99,
                        "unitPrice": 1.7495,
                        "revenue": 17495,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B09CKT5B9C"
            },
            {
                        "id": "13",
                        "name": "ENERLITES Decorator Paddle Rocker Light Switch, Gloss Finish, Single Pole, 3 Wire, Grounding Screw, Residential Grade, 15A 120V/277V, UL Listed, 91150-W-10PCS, White (10 Pack)",
                        "brand": "ENERLITES Store",
                        "price": 17.99,
                        "unitPrice": 1.8,
                        "revenue": 16190,
                        "volume": 900,
                        "url": "https://www.amazon.com/dp/B00QXOSTFU"
            },
            {
                        "id": "14",
                        "name": "ELEGRP Matte White Single Pole Decorator Light Switch 15Amp, 120-277V, Paddle Rocker Replacement, On/Off Wall Switch, Self-Grounding, Residential Grade, w/Wall Plate, UL/CUL (10 Pack)",
                        "brand": "ELEGRP",
                        "price": 31.99,
                        "unitPrice": 3.2,
                        "revenue": 15995,
                        "volume": 500,
                        "url": "https://www.amazon.com/dp/B09MW38VK7"
            },
            {
                        "id": "15",
                        "name": "Amazon Basics Smart Switch, Single Pole, Works with Alexa Only, 2.4 GHz Wi-Fi, No Hub Required, White",
                        "brand": "Amazon",
                        "price": 15.09,
                        "unitPrice": 15.09,
                        "revenue": 15090,
                        "volume": 1000,
                        "url": "https://www.amazon.com/dp/B095X911T8"
            }
]
        }
      ]
    },
    pricingAnalysis: {
      "priceDistribution": [
            {
                  "category": "Dimmer Switches",
                  "skuPrices": [
                        19.99,
                        59.99,
                        14.07,
                        89.99,
                        42.99,
                        16.99,
                        44.99,
                        62.99,
                        24.95,
                        19.98,
                        19.47,
                        38.96,
                        56.76,
                        62.99,
                        11.99,
                        39.99,
                        15.32,
                        629.55,
                        12.99,
                        65.99,
                        11.99,
                        23.28,
                        53.99,
                        88.99,
                        14.99,
                        77.99,
                        29.99,
                        47.44,
                        54.99,
                        24.99,
                        15.14,
                        17.99,
                        43.99,
                        42.95,
                        18.95,
                        35.75,
                        57.95,
                        23.52,
                        13.99,
                        47.0,
                        52.99,
                        59.99,
                        39.99,
                        47.99,
                        14.93,
                        4.84,
                        189.9,
                        53.99,
                        38.15,
                        69.99,
                        39.95,
                        25.99,
                        15.38,
                        23.99,
                        46.99,
                        52.99,
                        19.99,
                        38.87,
                        34.95,
                        108.53,
                        26.74,
                        8.99,
                        14.39,
                        23.99,
                        22.38,
                        27.41,
                        23.99,
                        23.99,
                        18.99,
                        68.95,
                        78.0,
                        69.95,
                        22.49,
                        39.99,
                        27.99,
                        16.99,
                        21.99,
                        71.38,
                        43.95,
                        22.97,
                        46.2,
                        11.99,
                        12.99,
                        76.99,
                        18.69,
                        65.95,
                        31.0,
                        21.99,
                        24.76,
                        39.79,
                        14.99,
                        52.99,
                        34.88,
                        139.95,
                        13.98,
                        13.99,
                        23.59,
                        25.99,
                        26.54,
                        19.29,
                        59.91,
                        29.99,
                        19.99,
                        44.97,
                        47.59,
                        81.0,
                        16.92,
                        58.95,
                        41.35,
                        39.13,
                        67.99,
                        68.99,
                        38.1,
                        19.99,
                        29.99,
                        14.99,
                        9.99,
                        53.29,
                        13.96,
                        39.99,
                        28.49,
                        39.99,
                        21.99,
                        77.22,
                        48.14,
                        18.99,
                        52.84,
                        18.65,
                        32.32,
                        46.99,
                        54.99,
                        51.78,
                        37.0,
                        11.18,
                        38.95,
                        9.99,
                        73.9,
                        24.11,
                        18.41,
                        19.99,
                        72.99,
                        69.99,
                        27.99,
                        29.99,
                        15.99,
                        0.0,
                        15.99,
                        23.47,
                        89.99,
                        37.99,
                        35.49
                  ],
                  "unitPrices": [
                        19.99,
                        30.0,
                        14.07,
                        9.0,
                        42.99,
                        8.5,
                        7.5,
                        10.5,
                        24.95,
                        19.98,
                        19.47,
                        38.96,
                        28.38,
                        21.0,
                        11.99,
                        6.67,
                        15.32,
                        69.95,
                        12.99,
                        16.5,
                        11.99,
                        23.28,
                        9.0,
                        8.9,
                        14.99,
                        7.8,
                        29.99,
                        47.44,
                        9.17,
                        6.25,
                        15.14,
                        17.99,
                        22.0,
                        42.95,
                        18.95,
                        11.92,
                        57.95,
                        23.52,
                        13.99,
                        15.666666666666666,
                        52.99,
                        59.99,
                        20.0,
                        12.0,
                        14.93,
                        4.84,
                        94.95,
                        53.99,
                        38.15,
                        11.67,
                        39.95,
                        25.99,
                        15.38,
                        12.0,
                        46.99,
                        13.25,
                        19.99,
                        38.87,
                        34.95,
                        108.53,
                        26.74,
                        8.99,
                        7.2,
                        23.99,
                        22.38,
                        27.41,
                        23.99,
                        23.99,
                        9.5,
                        68.95,
                        78.0,
                        69.95,
                        3.98,
                        13.33,
                        27.99,
                        1.31,
                        10.995,
                        71.38,
                        43.95,
                        22.97,
                        46.2,
                        11.99,
                        1.3,
                        76.99,
                        18.69,
                        32.975,
                        31.0,
                        21.99,
                        24.76,
                        39.79,
                        14.99,
                        13.25,
                        34.88,
                        139.95,
                        6.99,
                        13.99,
                        5.49,
                        13.0,
                        26.54,
                        19.29,
                        59.91,
                        29.99,
                        19.99,
                        44.97,
                        47.59,
                        81.0,
                        16.92,
                        58.95,
                        41.35,
                        39.13,
                        17.0,
                        17.25,
                        38.1,
                        19.99,
                        29.99,
                        14.99,
                        5.0,
                        53.29,
                        6.98,
                        39.99,
                        9.5,
                        39.99,
                        11.0,
                        77.22,
                        48.14,
                        18.99,
                        52.84,
                        18.65,
                        32.32,
                        23.5,
                        54.99,
                        51.78,
                        37.0,
                        11.18,
                        38.95,
                        9.99,
                        73.9,
                        24.11,
                        18.41,
                        19.99,
                        7.3,
                        17.5,
                        9.33,
                        29.99,
                        15.99,
                        0.0,
                        8.0,
                        23.47,
                        7.5,
                        7.6,
                        35.49
                  ],
                  "stats": {
                        "sku": {
                              "min": 0.0,
                              "q1": 19.47,
                              "median": 32.32,
                              "mean": 42.4645033112582,
                              "q3": 52.99,
                              "max": 629.55
                        },
                        "unit": {
                              "min": 1.3,
                              "q1": 12.0,
                              "median": 21.0,
                              "mean": 28.367044444444414,
                              "q3": 38.96,
                              "max": 139.95
                        }
                  }
            },
            {
                  "category": "Light Switches",
                  "skuPrices": [
                        6.74,
                        9.99,
                        58.4,
                        29.92,
                        19.99,
                        37.99,
                        63.99,
                        43.99,
                        41.9,
                        8.39,
                        64.95,
                        18.99,
                        13.99,
                        11.2,
                        39.99,
                        9.89,
                        21.99,
                        13.99,
                        29.98,
                        3.75,
                        13.9,
                        18.99,
                        9.99,
                        17.43,
                        15.09,
                        8.99,
                        17.69,
                        25.98,
                        42.99,
                        3.52,
                        31.99,
                        17.99,
                        17.99,
                        49.99,
                        15.99,
                        7.53,
                        16.99,
                        11.74,
                        33.99,
                        28.88,
                        34.99,
                        17.79,
                        59.95,
                        85.99,
                        16.69,
                        28.49,
                        5.0,
                        16.69,
                        11.45,
                        16.99,
                        2.68,
                        32.99,
                        0.0,
                        7.8,
                        11.99,
                        11.92,
                        9.55,
                        58.9,
                        16.15,
                        9.28,
                        3.65,
                        7.46,
                        10.33,
                        15.99,
                        12.46,
                        13.99,
                        6.79,
                        27.99,
                        12.99,
                        41.49,
                        9.98,
                        20.99,
                        8.99,
                        14.3,
                        15.99,
                        25.99,
                        7.82,
                        28.17,
                        12.99,
                        14.39,
                        20.97,
                        17.0,
                        28.0,
                        20.79,
                        43.99,
                        26.69,
                        15.94,
                        15.25,
                        15.95,
                        69.34,
                        19.99,
                        19.79,
                        36.89,
                        37.84,
                        31.99,
                        3.58,
                        19.98,
                        32.99,
                        9.99,
                        8.99,
                        37.98,
                        4.35,
                        24.99,
                        10.41,
                        23.99,
                        6.98,
                        26.99,
                        13.99,
                        37.99,
                        9.99,
                        28.99,
                        17.88,
                        4.35,
                        9.99,
                        12.99,
                        9.99,
                        23.99,
                        18.99,
                        6.79,
                        5.59,
                        7.48,
                        16.99,
                        13.98,
                        10.79,
                        5.65,
                        49.99,
                        13.72,
                        13.48,
                        18.99,
                        10.19,
                        49.99,
                        5.2,
                        39.99,
                        9.99,
                        19.2,
                        39.49,
                        26.99
                  ],
                  "unitPrices": [
                        6.74,
                        9.99,
                        14.6,
                        5.98,
                        19.99,
                        9.5,
                        6.4,
                        43.99,
                        13.966666666666667,
                        2.38,
                        64.95,
                        1.9,
                        13.99,
                        11.2,
                        10.0,
                        9.89,
                        4.4,
                        7.0,
                        29.98,
                        3.75,
                        13.9,
                        9.5,
                        9.99,
                        17.43,
                        15.09,
                        1.798,
                        1.77,
                        2.6,
                        14.33,
                        3.52,
                        3.2,
                        1.8,
                        1.8,
                        1.67,
                        1.6,
                        0.753,
                        16.99,
                        2.35,
                        17.0,
                        7.22,
                        1.7495,
                        1.779,
                        59.95,
                        1.72,
                        1.67,
                        1.42,
                        5.0,
                        1.67,
                        11.45,
                        3.4,
                        2.68,
                        3.3,
                        0.0,
                        7.8,
                        2.4,
                        11.92,
                        4.78,
                        5.89,
                        16.15,
                        9.28,
                        3.65,
                        7.46,
                        10.33,
                        1.6,
                        12.46,
                        7.0,
                        6.79,
                        2.799,
                        12.99,
                        41.49,
                        9.98,
                        20.99,
                        2.25,
                        14.3,
                        15.99,
                        25.99,
                        7.82,
                        7.04,
                        12.99,
                        14.39,
                        20.97,
                        17.0,
                        28.0,
                        20.79,
                        43.99,
                        26.69,
                        15.94,
                        15.25,
                        15.95,
                        1.39,
                        1.67,
                        1.98,
                        1.84,
                        37.84,
                        31.99,
                        3.58,
                        2.0,
                        1.65,
                        9.99,
                        4.5,
                        3.7979999999999996,
                        4.35,
                        12.5,
                        10.41,
                        2.4,
                        6.98,
                        1.35,
                        2.8,
                        1.9,
                        9.99,
                        2.9,
                        8.94,
                        4.35,
                        5.0,
                        3.25,
                        2.0,
                        2.0,
                        9.5,
                        2.41,
                        5.59,
                        7.48,
                        16.99,
                        13.98,
                        10.79,
                        5.65,
                        12.5,
                        13.72,
                        13.48,
                        1.9,
                        10.19,
                        49.99,
                        5.2,
                        39.99,
                        9.99,
                        19.2,
                        39.49,
                        6.75
                  ],
                  "stats": {
                        "sku": {
                              "min": 0.0,
                              "q1": 9.99,
                              "median": 16.69,
                              "mean": 21.248029197080257,
                              "q3": 28.17,
                              "max": 85.99
                        },
                        "unit": {
                              "min": 0.753,
                              "q1": 2.799,
                              "median": 7.48,
                              "mean": 11.102523284313731,
                              "q3": 14.3,
                              "max": 64.95
                        }
                  }
            }
      ],
      "brandPriceDistribution": [
            {
                  "category": "Dimmer Switches",
                  "brands": [
                        {
                              "name": "Lutron",
                              "skuPrices": [
                                    19.47,
                                    56.76,
                                    629.55,
                                    23.28,
                                    18.95,
                                    57.95,
                                    23.52,
                                    52.99,
                                    189.9,
                                    39.95,
                                    34.95,
                                    108.53,
                                    68.95,
                                    78.0,
                                    69.95,
                                    71.38,
                                    22.97,
                                    46.2,
                                    65.95,
                                    139.95,
                                    81.0,
                                    16.92,
                                    58.95,
                                    39.13,
                                    48.14,
                                    32.32,
                                    37.0,
                                    38.95,
                                    73.9,
                                    0.0,
                                    35.49
                              ],
                              "unitPrices": [
                                    19.47,
                                    28.38,
                                    69.95,
                                    23.28,
                                    18.95,
                                    57.95,
                                    23.52,
                                    52.99,
                                    94.95,
                                    39.95,
                                    34.95,
                                    108.53,
                                    68.95,
                                    78.0,
                                    69.95,
                                    71.38,
                                    22.97,
                                    46.2,
                                    32.975,
                                    139.95,
                                    81.0,
                                    16.92,
                                    58.95,
                                    39.13,
                                    48.14,
                                    32.32,
                                    37.0,
                                    38.95,
                                    73.9,
                                    0.0,
                                    35.49
                              ]
                        },
                        {
                              "name": "GE",
                              "skuPrices": [
                                    44.99,
                                    15.32,
                                    14.99,
                                    42.95,
                                    53.99,
                                    38.87,
                                    27.41,
                                    18.99,
                                    22.49,
                                    21.99,
                                    76.99,
                                    13.98,
                                    23.59,
                                    25.99,
                                    14.99,
                                    13.96,
                                    52.84,
                                    51.78,
                                    11.18,
                                    9.99,
                                    29.99,
                                    89.99
                              ],
                              "unitPrices": [
                                    7.5,
                                    15.32,
                                    14.99,
                                    42.95,
                                    53.99,
                                    38.87,
                                    27.41,
                                    9.5,
                                    3.98,
                                    10.995,
                                    76.99,
                                    6.99,
                                    5.49,
                                    13.0,
                                    14.99,
                                    6.98,
                                    52.84,
                                    51.78,
                                    11.18,
                                    9.99,
                                    29.99,
                                    7.5
                              ]
                        },
                        {
                              "name": "Leviton",
                              "skuPrices": [
                                    14.07,
                                    24.95,
                                    38.96,
                                    11.99,
                                    17.99,
                                    47.0,
                                    4.84,
                                    38.15,
                                    46.99,
                                    22.38,
                                    23.99,
                                    24.76,
                                    59.91,
                                    47.59,
                                    41.35,
                                    38.1,
                                    54.99,
                                    18.41
                              ],
                              "unitPrices": [
                                    14.07,
                                    24.95,
                                    38.96,
                                    11.99,
                                    17.99,
                                    15.666666666666666,
                                    4.84,
                                    38.15,
                                    46.99,
                                    22.38,
                                    23.99,
                                    24.76,
                                    59.91,
                                    47.59,
                                    41.35,
                                    38.1,
                                    54.99,
                                    18.41
                              ]
                        },
                        {
                              "name": "BESTTEN",
                              "skuPrices": [
                                    16.99,
                                    39.99,
                                    53.99,
                                    77.99,
                                    11.99,
                                    14.99,
                                    28.49,
                                    72.99,
                                    27.99,
                                    37.99
                              ],
                              "unitPrices": [
                                    8.5,
                                    6.67,
                                    9.0,
                                    7.8,
                                    11.99,
                                    14.99,
                                    9.5,
                                    7.3,
                                    9.33,
                                    7.6
                              ]
                        },
                        {
                              "name": "Legrand",
                              "skuPrices": [
                                    47.44,
                                    39.79,
                                    34.88,
                                    26.54,
                                    53.29,
                                    77.22,
                                    24.11,
                                    23.47
                              ],
                              "unitPrices": [
                                    47.44,
                                    39.79,
                                    34.88,
                                    26.54,
                                    53.29,
                                    77.22,
                                    24.11,
                                    23.47
                              ]
                        },
                        {
                              "name": "ELEGRP",
                              "skuPrices": [
                                    59.99,
                                    89.99,
                                    62.99,
                                    88.99,
                                    24.99,
                                    19.99,
                                    12.99
                              ],
                              "unitPrices": [
                                    30.0,
                                    9.0,
                                    10.5,
                                    8.9,
                                    6.25,
                                    19.99,
                                    1.3
                              ]
                        },
                        {
                              "name": "TREATLIFE",
                              "skuPrices": [
                                    29.99,
                                    23.99,
                                    19.99,
                                    67.99,
                                    46.99,
                                    69.99
                              ],
                              "unitPrices": [
                                    29.99,
                                    23.99,
                                    19.99,
                                    17.0,
                                    23.5,
                                    17.5
                              ]
                        },
                        {
                              "name": "Amazon",
                              "skuPrices": [
                                    19.99,
                                    18.69,
                                    44.97,
                                    29.99,
                                    19.99
                              ],
                              "unitPrices": [
                                    19.99,
                                    18.69,
                                    44.97,
                                    29.99,
                                    19.99
                              ]
                        }
                  ]
            },
            {
                  "category": "Light Switches",
                  "brands": [
                        {
                              "name": "Leviton",
                              "skuPrices": [
                                    11.2,
                                    13.9,
                                    25.98,
                                    3.52,
                                    7.53,
                                    11.45,
                                    2.68,
                                    7.8,
                                    11.92,
                                    9.28,
                                    12.46,
                                    9.98,
                                    7.82,
                                    17.0,
                                    43.99,
                                    26.69,
                                    15.25,
                                    15.95,
                                    37.84,
                                    19.98,
                                    37.98,
                                    4.35,
                                    10.41,
                                    4.35,
                                    5.59,
                                    13.98,
                                    5.65,
                                    13.72,
                                    13.48,
                                    5.2,
                                    19.2,
                                    39.49
                              ],
                              "unitPrices": [
                                    11.2,
                                    13.9,
                                    2.6,
                                    3.52,
                                    0.753,
                                    11.45,
                                    2.68,
                                    7.8,
                                    11.92,
                                    9.28,
                                    12.46,
                                    9.98,
                                    7.82,
                                    17.0,
                                    43.99,
                                    26.69,
                                    15.25,
                                    15.95,
                                    37.84,
                                    2.0,
                                    3.7979999999999996,
                                    4.35,
                                    10.41,
                                    4.35,
                                    5.59,
                                    13.98,
                                    5.65,
                                    13.72,
                                    13.48,
                                    5.2,
                                    19.2,
                                    39.49
                              ]
                        },
                        {
                              "name": "ENERLITES Store",
                              "skuPrices": [
                                    9.99,
                                    29.92,
                                    63.99,
                                    17.99,
                                    15.99,
                                    11.99,
                                    10.33,
                                    12.99,
                                    19.79,
                                    37.99
                              ],
                              "unitPrices": [
                                    9.99,
                                    5.98,
                                    6.4,
                                    1.8,
                                    1.6,
                                    2.4,
                                    10.33,
                                    12.99,
                                    1.98,
                                    1.9
                              ]
                        },
                        {
                              "name": "ELEGRP",
                              "skuPrices": [
                                    31.99,
                                    17.79,
                                    16.99,
                                    32.99,
                                    9.99,
                                    13.99,
                                    9.99,
                                    28.99,
                                    9.99
                              ],
                              "unitPrices": [
                                    3.2,
                                    1.779,
                                    3.4,
                                    3.3,
                                    9.99,
                                    2.8,
                                    9.99,
                                    2.9,
                                    2.0
                              ]
                        },
                        {
                              "name": "GE",
                              "skuPrices": [
                                    13.99,
                                    8.99,
                                    11.74,
                                    5.0,
                                    25.99,
                                    12.99,
                                    14.39,
                                    16.99,
                                    9.99
                              ],
                              "unitPrices": [
                                    13.99,
                                    1.798,
                                    2.35,
                                    5.0,
                                    25.99,
                                    12.99,
                                    14.39,
                                    16.99,
                                    9.99
                              ]
                        },
                        {
                              "name": "Legrand",
                              "skuPrices": [
                                    58.4,
                                    3.75,
                                    3.65,
                                    6.79,
                                    3.58,
                                    10.79
                              ],
                              "unitPrices": [
                                    14.6,
                                    3.75,
                                    3.65,
                                    6.79,
                                    3.58,
                                    10.79
                              ]
                        },
                        {
                              "name": "BESTTEN",
                              "skuPrices": [
                                    17.69,
                                    85.99,
                                    16.69,
                                    13.99,
                                    23.99,
                                    26.99
                              ],
                              "unitPrices": [
                                    1.77,
                                    1.72,
                                    1.67,
                                    7.0,
                                    2.4,
                                    6.75
                              ]
                        },
                        {
                              "name": "Lutron",
                              "skuPrices": [
                                    64.95,
                                    17.43,
                                    59.95,
                                    15.94,
                                    6.98,
                                    7.48
                              ],
                              "unitPrices": [
                                    64.95,
                                    17.43,
                                    59.95,
                                    15.94,
                                    6.98,
                                    7.48
                              ]
                        },
                        {
                              "name": "ThunderWay",
                              "skuPrices": [
                                    13.99,
                                    17.99,
                                    16.69,
                                    32.99,
                                    18.99
                              ],
                              "unitPrices": [
                                    7.0,
                                    1.8,
                                    1.67,
                                    1.65,
                                    1.9
                              ]
                        }
                  ]
            }
      ]
},
    marketInsights: {
      "segmentRevenue": {
            "dimmerSwitches": [
                  {
                        "segment": "Smart Wi-Fi Enabled Dimmer Switches",
                        "revenue": 377465,
                        "products": 30
                  },
                  {
                        "segment": "Smart Hub-Dependent Dimmer Switches",
                        "revenue": 340089,
                        "products": 16
                  },
                  {
                        "segment": "Slide Control Dimmer Switches",
                        "revenue": 276384,
                        "products": 26
                  },
                  {
                        "segment": "LED Optimized Dimmer Switches",
                        "revenue": 118475,
                        "products": 18
                  },
                  {
                        "segment": "Plug-In Portable Dimmer Controls",
                        "revenue": 58964,
                        "products": 7
                  },
                  {
                        "segment": "Dual Circuit Dimmer Switches",
                        "revenue": 35690,
                        "products": 1
                  },
                  {
                        "segment": "Toggle Style Dimmer Switches",
                        "revenue": 26654,
                        "products": 5
                  },
                  {
                        "segment": "Multi-Location Companion Dimmer Switches",
                        "revenue": 26379,
                        "products": 3
                  },
                  {
                        "segment": "Rocker Style Dimmer Switches",
                        "revenue": 19894,
                        "products": 10
                  },
                  {
                        "segment": "Universal Multi-Load Dimmer Switches",
                        "revenue": 18433,
                        "products": 3
                  },
                  {
                        "segment": "Multi-Function Timer Dimmer Switches",
                        "revenue": 13790,
                        "products": 1
                  },
                  {
                        "segment": "Commercial 0-10V Dimmer Switches",
                        "revenue": 13403,
                        "products": 7
                  },
                  {
                        "segment": "Rotary Knob Dimmer Switches",
                        "revenue": 12678,
                        "products": 7
                  },
                  {
                        "segment": "Touch Activated Dimmer Switches",
                        "revenue": 9989,
                        "products": 4
                  },
                  {
                        "segment": "Fan and Light Combination Dimmer Controls",
                        "revenue": 9874,
                        "products": 2
                  },
                  {
                        "segment": "Electronic Low Voltage Dimmer Switches",
                        "revenue": 7800,
                        "products": 2
                  },
                  {
                        "segment": "Incandescent Compatible Dimmer Switches",
                        "revenue": 2699,
                        "products": 3
                  },
                  {
                        "segment": "USB Powered Dimmer Switches",
                        "revenue": 949,
                        "products": 2
                  },
                  {
                        "segment": "Digital Display Dimmer Switches",
                        "revenue": 0,
                        "products": 3
                  },
                  {
                        "segment": "Handheld Remote Control Dimmer Switches",
                        "revenue": 0,
                        "products": 1
                  }
            ],
            "lightSwitches": [
                  {
                        "segment": "WiFi Connected Smart Switches",
                        "revenue": 417004,
                        "products": 21
                  },
                  {
                        "segment": "Single Pole Rocker Switches",
                        "revenue": 189067,
                        "products": 30
                  },
                  {
                        "segment": "Three Way Multi-Location Control Switches",
                        "revenue": 57189,
                        "products": 13
                  },
                  {
                        "segment": "Smart Hub Dependent Switches",
                        "revenue": 53058,
                        "products": 6
                  },
                  {
                        "segment": "Multi-Function Combination Switches",
                        "revenue": 35021,
                        "products": 15
                  },
                  {
                        "segment": "RF Wireless Remote Control Switches",
                        "revenue": 33376,
                        "products": 5
                  },
                  {
                        "segment": "LED Illuminated Indicator Switches",
                        "revenue": 29862,
                        "products": 13
                  },
                  {
                        "segment": "Single Pole Toggle Switches",
                        "revenue": 28307,
                        "products": 17
                  },
                  {
                        "segment": "Four Way Multi-Location Control Switches",
                        "revenue": 12255,
                        "products": 9
                  },
                  {
                        "segment": "Specialty Environmental Control Switches",
                        "revenue": 7898,
                        "products": 1
                  },
                  {
                        "segment": "High Amperage Rocker Switches",
                        "revenue": 2236,
                        "products": 1
                  },
                  {
                        "segment": "Dimmer Switches",
                        "revenue": 1430,
                        "products": 1
                  },
                  {
                        "segment": "Switch Outlet Combination Devices",
                        "revenue": 1399,
                        "products": 1
                  },
                  {
                        "segment": "Add On Auxiliary Switches",
                        "revenue": 807,
                        "products": 1
                  },
                  {
                        "segment": "Multi-Feature Combination Control Switches",
                        "revenue": 0,
                        "products": 1
                  },
                  {
                        "segment": "Inline Cord Control Switches",
                        "revenue": 0,
                        "products": 1
                  },
                  {
                        "segment": "Sound Activated Switches",
                        "revenue": 0,
                        "products": 1
                  }
            ]
      }
},
    summaryMetrics: {
      "priceRange": "$0.00 - $629.55",
      "avgVolumePerProduct": 280.38194444444446,
      "medianPrice": 23.494999999999997,
      "majorBrands": 4
}
  };
}
